### PR TITLE
[blocked by discussion in Microsoft/TypeScript repo] Fix property initializers with block scoped bindings

### PR DESCRIPTION
**Pull request by joeywatts**
Fixes https://github.com/Microsoft/TypeScript/issues/27864#issuecomment-443038174

### CODE REVIEW

**Comment by mheiber** [comment]
Once we settle on a solution in https://github.com/Microsoft/TypeScript/pull/28708 (which is on a divergent history), we can forward-port the changes here and then merge

**Comment by mheiber** [comment]
closing because superseded by PR against upstream: https://github.com/Microsoft/TypeScript/pull/28708

**Comment by joeywatts** [comment]
@mheiber I think this is distinct from that PR (but depends on a helper function defined in that PR)

**Comment by mheiber** [comment]
@joeywatts closing for now, I think this is out of date. Please re-open if closing in error

**Pull request closed without merging**
